# Generated by Django 2.2.6 on 2019-10-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=99)),
                ('store_id', models.CharField(max_length=20)),
                ('visit_day', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
            ],
        ),
    ]
