# Generated by Django 2.2.6 on 2019-10-25 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_remove_coordinator_store'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='coord_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coordinator.Coordinator'),
            preserve_default=False,
        ),
    ]
