# Generated by Django 2.2.6 on 2019-10-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191024_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=20, verbose_name='ID da loja'),
        ),
        migrations.AlterField(
            model_name='store',
            name='visit_day',
            field=models.DateField(verbose_name='Dia da Visita'),
        ),
    ]
