# Generated by Django 2.2.6 on 2019-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='id_sf',
            field=models.CharField(max_length=18, verbose_name='ID Salesforce'),
        ),
    ]
