# Generated by Django 2.2.6 on 2019-10-25 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
            preserve_default=False,
        ),
    ]
