# Generated by Django 2.2.6 on 2019-10-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_coordinator_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='store',
        ),
    ]
